# slightly influenced by https://github.com/PistonDevelopers/piston-examples/blob/a473c4baa1262bbf6916b677f3bdcde2b6d3c1b5/.travis.yml
language: rust
rust:
  - stable
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev
script:
  - cargo build -v
  - cargo test